name: Deployment Workflow
on:
  push:
    branches: 
      - main
    
    paths: 
      - BackendxFrontend/Frontend/**

jobs:
  deploy:
    name: Deployment Workflow
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: install ssh key
      uses: caberger/install-ssh-key@v1.0
      with:
        ssh-private-key:  ${{ secrets.SSH_PRIVATE_KEY }}
        user: ${{ secrets.SERVER_USER }}
        server: ${{ secrets.SERVER }}
        alias: leopvvusalizer
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true
        
    - name: test ssh
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null leopvvusalizer ls -l
    - name: deploy to server
      run: |
        scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null * leopvvusalizer:/var/www/html 
      working-directory: BackendxFrontend/Frontend
